development:
  adapter: postgresql
  encoding: unicode
  database: stock_dev
  pool: 5
  username: user
  password: user1234
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: stock_prod
  pool: 5
  username: user
  password: user1234
  host: localhost