 postgres:
  hostname: localhost
  port: 5432
  username: you
  password: password
  database: pg-db

production:
  adapter: postgresql
  encoding: unicode
  database: stock_prod
  pool: 5
  username: user
  password: user1234
  host: localhost