development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

production:
  adapter: postgresql
  encoding: unicode
  database: stock_prod
  pool: 5
  username: user
  password: user1234
  host: localhost